24.08.2013 14:19:41 ERROR LoggiApp [main] Exception initializing Configuration Service
org.h2.jdbc.JdbcSQLException: Feature not supported: "-web,-webAllowOthers,true,-webPort,8082" [50100-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.util.Tool.throwUnsupportedOption(Tool.java:66)
	at org.h2.tools.Server.verifyArgs(Server.java:139)
	at org.h2.tools.Server.<init>(Server.java:48)
	at org.h2.tools.Server.createWebServer(Server.java:413)
	at de.dmc.loggi.service.impl.H2WriteServiceImpl.initialize(H2WriteServiceImpl.java:59)
	at de.dmc.loggi.LoggiApp.start(LoggiApp.java:53)
	at de.dmc.loggi.LoggiApp.main(LoggiApp.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
24.08.2013 14:31:18 ERROR LoggiApp [main] Exception initializing Configuration Service
org.h2.jdbc.JdbcSQLException: Feature not supported: "true" [50100-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.util.Tool.throwUnsupportedOption(Tool.java:66)
	at org.h2.tools.Server.verifyArgs(Server.java:204)
	at org.h2.tools.Server.<init>(Server.java:48)
	at org.h2.tools.Server.createWebServer(Server.java:413)
	at de.dmc.loggi.service.impl.H2WriteServiceImpl.initialize(H2WriteServiceImpl.java:61)
	at de.dmc.loggi.LoggiApp.start(LoggiApp.java:53)
	at de.dmc.loggi.LoggiApp.main(LoggiApp.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
24.08.2013 14:31:36 ERROR LoggiApp [main] Exception initializing Configuration Service
org.h2.jdbc.JdbcSQLException: Feature not supported: "-webAllowOthers true" [50100-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.util.Tool.throwUnsupportedOption(Tool.java:66)
	at org.h2.tools.Server.verifyArgs(Server.java:139)
	at org.h2.tools.Server.<init>(Server.java:48)
	at org.h2.tools.Server.createWebServer(Server.java:413)
	at de.dmc.loggi.service.impl.H2WriteServiceImpl.initialize(H2WriteServiceImpl.java:61)
	at de.dmc.loggi.LoggiApp.start(LoggiApp.java:53)
	at de.dmc.loggi.LoggiApp.main(LoggiApp.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
24.08.2013 14:33:08 ERROR LoggiApp [main] Exception initializing Configuration Service
org.h2.jdbc.JdbcSQLException: Feature not supported: "-webPort 8082" [50100-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.util.Tool.throwUnsupportedOption(Tool.java:66)
	at org.h2.tools.Server.verifyArgs(Server.java:139)
	at org.h2.tools.Server.<init>(Server.java:48)
	at org.h2.tools.Server.createWebServer(Server.java:413)
	at de.dmc.loggi.service.impl.H2WriteServiceImpl.initialize(H2WriteServiceImpl.java:61)
	at de.dmc.loggi.LoggiApp.start(LoggiApp.java:53)
	at de.dmc.loggi.LoggiApp.main(LoggiApp.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
24.08.2013 14:34:13 ERROR H2WriteServiceImpl [ColumnProcessor1] Exception processing record
org.h2.jdbc.JdbcSQLException: Table "RECORDS" not found; SQL statement:
insert into records(date,level) values ('21.08.2013','ERROR') [42102-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.command.Parser.readTableOrView(Parser.java:4864)
	at org.h2.command.Parser.readTableOrView(Parser.java:4842)
	at org.h2.command.Parser.parseInsert(Parser.java:974)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:428)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at de.dmc.loggi.service.impl.H2WriteServiceImpl.processRecord(H2WriteServiceImpl.java:46)
	at de.dmc.loggi.service.impl.ReadServiceImpl$RecordTask.call(ReadServiceImpl.java:95)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
24.08.2013 14:34:13 ERROR H2WriteServiceImpl [ColumnProcessor3] Exception processing record
org.h2.jdbc.JdbcSQLException: Table "RECORDS" not found; SQL statement:
insert into records(date,level) values ('23.08.2013','ERROR') [42102-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.command.Parser.readTableOrView(Parser.java:4864)
	at org.h2.command.Parser.readTableOrView(Parser.java:4842)
	at org.h2.command.Parser.parseInsert(Parser.java:974)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:428)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at de.dmc.loggi.service.impl.H2WriteServiceImpl.processRecord(H2WriteServiceImpl.java:46)
	at de.dmc.loggi.service.impl.ReadServiceImpl$RecordTask.call(ReadServiceImpl.java:95)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
24.08.2013 14:34:13 ERROR H2WriteServiceImpl [ColumnProcessor2] Exception processing record
org.h2.jdbc.JdbcSQLException: Table "RECORDS" not found; SQL statement:
insert into records(date,level) values ('22.08.2013','ERROR') [42102-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.command.Parser.readTableOrView(Parser.java:4864)
	at org.h2.command.Parser.readTableOrView(Parser.java:4842)
	at org.h2.command.Parser.parseInsert(Parser.java:974)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:428)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at de.dmc.loggi.service.impl.H2WriteServiceImpl.processRecord(H2WriteServiceImpl.java:46)
	at de.dmc.loggi.service.impl.ReadServiceImpl$RecordTask.call(ReadServiceImpl.java:95)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
24.08.2013 15:47:31 ERROR LoggiApp [main] Exception initializing Configuration Service
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE RECORDS(DATE VARCHAR(NULL[*]), LEVEL VARCHAR(NULL)) "; expected "long"; SQL statement:
create table records(date varchar(null), level varchar(null)) [42001-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.getSyntaxError(DbException.java:196)
	at org.h2.command.Parser.readLong(Parser.java:2772)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3739)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3586)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5318)
	at org.h2.command.Parser.parseCreate(Parser.java:3873)
	at org.h2.command.Parser.parsePrepared(Parser.java:324)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:428)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at de.dmc.loggi.service.impl.H2WriteServiceImpl.initialize(H2WriteServiceImpl.java:80)
	at de.dmc.loggi.LoggiApp.start(LoggiApp.java:53)
	at de.dmc.loggi.LoggiApp.main(LoggiApp.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
24.08.2013 15:52:24 ERROR LoggiApp [main] Exception initializing Configuration Service
org.h2.jdbc.JdbcSQLException: Exception opening port "8082" (port may be in use), cause: "java.net.BindException: Address already in use" [90061-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:160)
	at org.h2.util.NetUtils.createServerSocketTry(NetUtils.java:190)
	at org.h2.util.NetUtils.createServerSocket(NetUtils.java:156)
	at org.h2.server.web.WebServer.start(WebServer.java:336)
	at org.h2.tools.Server.start(Server.java:459)
	at de.dmc.loggi.service.impl.H2WriteServiceImpl.initialize(H2WriteServiceImpl.java:64)
	at de.dmc.loggi.LoggiApp.start(LoggiApp.java:53)
	at de.dmc.loggi.LoggiApp.main(LoggiApp.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
Caused by: java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:376)
	at java.net.ServerSocket.bind(ServerSocket.java:376)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at java.net.ServerSocket.<init>(ServerSocket.java:128)
	at org.h2.util.NetUtils.createServerSocketTry(NetUtils.java:186)
	... 11 more
24.08.2013 15:54:01 ERROR LoggiApp [main] Exception initializing Configuration Service
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE RECORDS(DATE VARCHAR(NULL[*]), LEVEL VARCHAR(NULL)) "; expected "long"; SQL statement:
create table records(date varchar(null), level varchar(null)) [42001-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.getSyntaxError(DbException.java:196)
	at org.h2.command.Parser.readLong(Parser.java:2772)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3739)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3586)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5318)
	at org.h2.command.Parser.parseCreate(Parser.java:3873)
	at org.h2.command.Parser.parsePrepared(Parser.java:324)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:428)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at de.dmc.loggi.service.impl.H2WriteServiceImpl.initialize(H2WriteServiceImpl.java:80)
	at de.dmc.loggi.LoggiApp.start(LoggiApp.java:53)
	at de.dmc.loggi.LoggiApp.main(LoggiApp.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
24.08.2013 16:41:32 ERROR LoggiApp [main] Exception initializing Configuration Service
org.h2.jdbc.JdbcSQLException: Exception opening port "8082" (port may be in use), cause: "java.net.BindException: Address already in use" [90061-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:160)
	at org.h2.util.NetUtils.createServerSocketTry(NetUtils.java:190)
	at org.h2.util.NetUtils.createServerSocket(NetUtils.java:156)
	at org.h2.server.web.WebServer.start(WebServer.java:336)
	at org.h2.tools.Server.start(Server.java:459)
	at de.dmc.loggi.service.impl.H2WriteServiceImpl.initialize(H2WriteServiceImpl.java:64)
	at de.dmc.loggi.LoggiApp.start(LoggiApp.java:53)
	at de.dmc.loggi.LoggiApp.main(LoggiApp.java:35)
Caused by: java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:376)
	at java.net.ServerSocket.bind(ServerSocket.java:376)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at java.net.ServerSocket.<init>(ServerSocket.java:128)
	at org.h2.util.NetUtils.createServerSocketTry(NetUtils.java:186)
	... 6 more
24.08.2013 16:47:03 ERROR ConfigurationService [main] Exception instantiating column, name:date processor:de.dmc.loggi.processors.impl.RegexMatchProcessor
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at de.dmc.loggi.service.impl.ConfigurationServiceImpl.initializeColumn(ConfigurationServiceImpl.java:56)
	at de.dmc.loggi.service.impl.ConfigurationServiceImpl.initialize(ConfigurationServiceImpl.java:43)
	at de.dmc.loggi.LoggiApp.start(LoggiApp.java:51)
	at de.dmc.loggi.LoggiApp.main(LoggiApp.java:35)
Caused by: de.dmc.loggi.exceptions.ConfigurationException: Missing required attribute 'regex' for column 'date'
	at de.dmc.loggi.processors.AbstractColumnProcessor.<init>(AbstractColumnProcessor.java:41)
	at de.dmc.loggi.processors.impl.RegexMatchProcessor.<init>(RegexMatchProcessor.java:24)
	... 8 more
24.08.2013 16:47:40 ERROR ConfigurationService [main] Exception instantiating column, name:date processor:de.dmc.loggi.processors.impl.RegexMatchProcessor
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at de.dmc.loggi.service.impl.ConfigurationServiceImpl.initializeColumn(ConfigurationServiceImpl.java:56)
	at de.dmc.loggi.service.impl.ConfigurationServiceImpl.initialize(ConfigurationServiceImpl.java:43)
	at de.dmc.loggi.LoggiApp.start(LoggiApp.java:51)
	at de.dmc.loggi.LoggiApp.main(LoggiApp.java:35)
Caused by: de.dmc.loggi.exceptions.ConfigurationException: Missing required attribute 'regex' for column 'date'
	at de.dmc.loggi.processors.AbstractColumnProcessor.<init>(AbstractColumnProcessor.java:41)
	at de.dmc.loggi.processors.impl.RegexMatchProcessor.<init>(RegexMatchProcessor.java:24)
	... 8 more
24.08.2013 16:48:36 ERROR ConfigurationService [main] Exception instantiating column, name:date processor:de.dmc.loggi.processors.impl.RegexMatchProcessor
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at de.dmc.loggi.service.impl.ConfigurationServiceImpl.initializeColumn(ConfigurationServiceImpl.java:56)
	at de.dmc.loggi.service.impl.ConfigurationServiceImpl.initialize(ConfigurationServiceImpl.java:43)
	at de.dmc.loggi.LoggiApp.start(LoggiApp.java:51)
	at de.dmc.loggi.LoggiApp.main(LoggiApp.java:35)
Caused by: de.dmc.loggi.exceptions.ConfigurationException: Missing required attribute 'regex' for column 'date'
	at de.dmc.loggi.processors.AbstractColumnProcessor.<init>(AbstractColumnProcessor.java:41)
	at de.dmc.loggi.processors.impl.RegexMatchProcessor.<init>(RegexMatchProcessor.java:24)
	... 8 more
24.08.2013 16:48:36 ERROR LoggiApp [main] Exception initializing Configuration Service
org.h2.jdbc.JdbcSQLException: Exception opening port "8082" (port may be in use), cause: "java.net.BindException: Address already in use" [90061-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:160)
	at org.h2.util.NetUtils.createServerSocketTry(NetUtils.java:190)
	at org.h2.util.NetUtils.createServerSocket(NetUtils.java:156)
	at org.h2.server.web.WebServer.start(WebServer.java:336)
	at org.h2.tools.Server.start(Server.java:459)
	at de.dmc.loggi.service.impl.H2WriteServiceImpl.initialize(H2WriteServiceImpl.java:64)
	at de.dmc.loggi.LoggiApp.start(LoggiApp.java:53)
	at de.dmc.loggi.LoggiApp.main(LoggiApp.java:35)
Caused by: java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:376)
	at java.net.ServerSocket.bind(ServerSocket.java:376)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at java.net.ServerSocket.<init>(ServerSocket.java:128)
	at org.h2.util.NetUtils.createServerSocketTry(NetUtils.java:186)
	... 6 more
24.08.2013 16:48:55 ERROR ConfigurationService [main] Exception instantiating column, name:date processor:de.dmc.loggi.processors.impl.RegexMatchProcessor
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at de.dmc.loggi.service.impl.ConfigurationServiceImpl.initializeColumn(ConfigurationServiceImpl.java:56)
	at de.dmc.loggi.service.impl.ConfigurationServiceImpl.initialize(ConfigurationServiceImpl.java:43)
	at de.dmc.loggi.LoggiApp.start(LoggiApp.java:51)
	at de.dmc.loggi.LoggiApp.main(LoggiApp.java:35)
Caused by: de.dmc.loggi.exceptions.ConfigurationException: Missing required attribute 'regex' for column 'date'
	at de.dmc.loggi.processors.AbstractColumnProcessor.<init>(AbstractColumnProcessor.java:41)
	at de.dmc.loggi.processors.impl.RegexMatchProcessor.<init>(RegexMatchProcessor.java:24)
	... 8 more
24.08.2013 18:49:20 ERROR HelpServiceImpl [main] Exception compiling column processor usage info
java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at de.dmc.loggi.service.impl.HelpServiceImpl.printHelp(HelpServiceImpl.java:50)
	at de.dmc.loggi.LoggiApp.start(LoggiApp.java:50)
	at de.dmc.loggi.LoggiApp.main(LoggiApp.java:33)
24.08.2013 18:49:20 ERROR HelpServiceImpl [main] Exception compiling column processor usage info
java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at de.dmc.loggi.service.impl.HelpServiceImpl.printHelp(HelpServiceImpl.java:50)
	at de.dmc.loggi.LoggiApp.start(LoggiApp.java:50)
	at de.dmc.loggi.LoggiApp.main(LoggiApp.java:33)
24.08.2013 18:50:01 ERROR HelpServiceImpl [main] Exception compiling column processor usage info
java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at de.dmc.loggi.service.impl.HelpServiceImpl.printHelp(HelpServiceImpl.java:50)
	at de.dmc.loggi.LoggiApp.start(LoggiApp.java:50)
	at de.dmc.loggi.LoggiApp.main(LoggiApp.java:33)
24.08.2013 18:50:01 ERROR HelpServiceImpl [main] Exception compiling column processor usage info
java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at de.dmc.loggi.service.impl.HelpServiceImpl.printHelp(HelpServiceImpl.java:50)
	at de.dmc.loggi.LoggiApp.start(LoggiApp.java:50)
	at de.dmc.loggi.LoggiApp.main(LoggiApp.java:33)
24.08.2013 18:56:12 ERROR HelpServiceImpl [main] Exception compiling column processor usage info
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at de.dmc.loggi.service.impl.HelpServiceImpl.printHelp(HelpServiceImpl.java:50)
	at de.dmc.loggi.LoggiApp.start(LoggiApp.java:50)
	at de.dmc.loggi.LoggiApp.main(LoggiApp.java:33)
Caused by: de.dmc.loggi.exceptions.ConfigurationException: Missing required attribute 'regex' for column 'null'
	at de.dmc.loggi.processors.AbstractColumnProcessor.<init>(AbstractColumnProcessor.java:41)
	at de.dmc.loggi.processors.impl.RegexMatchProcessor.<init>(RegexMatchProcessor.java:24)
	... 7 more
